# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-1809 AS build
WORKDIR /App

# Copy everything from the current directory to the working directory
COPY . ./

# Restore dependencies
RUN dotnet restore

# Build and publish the application
RUN dotnet publish -c Release -o out

# Runtime image stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809
WORKDIR /App

# Copy the published output from the build stage to the working directory
COPY --from=build /App/out .

# Set environment variable to indicate running in a container
ENV DOTNET_RUNNING_IN_CONTAINER=true

# Execute the WeatherServiceDemo.exe as the entrypoint
ENTRYPOINT ["WeatherServiceDemo.exe"]