# This Dockerfile is used to build a .NET Core application image for the WeatherServiceDemo application.
# It follows a multi-stage build approach, where the first stage is used for building and the second stage is used for runtime.

# --------------------------------------------------------------------------------
# First Stage: Build Stage
# --------------------------------------------------------------------------------

# Set the base image to the .NET Core SDK 8.0
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set the working directory to /App
WORKDIR /App

# Copy all the files from the host to the container
COPY . ./

# Restore the dependencies for the application. This is done in a separate step to allow for layer caching.
RUN dotnet restore

# Build and publish the application in Release mode. The output is placed in the 'out' directory.